name: Block pull requests workflows

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: block
        run: |
          if [[ ${GITHUB_HEAD_REF} != dev ]];
          then
            echo "Error: Tried to create a pull request into 'main' branch from other than 'dev' branch."
            exit 1
          fi
