name: Build workflows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: init_author
        run: |
          git config --global user.name ${{secrets.USER_NAME}}
          git config --global user.email ${{secrets.USER_EMAIL}}
      - name: publish
        run: |
          cd FE
          npm install
          npm run deploy