name: Build workflows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: init_author
        run: |
          git config --global user.name ${{secrets.USER_NAME}}
          git config --global user.email ${{secrets.USER_EMAIL}}
          git config --global user.password ${{secrets.AUTH_TOKEN}}
      - name: publish
        run: |
          cd FE
          npm install
          npm pkg set author=${{secrets.USER_NAME}}
          npm pkg set homepage=${{secrets.HOME_PAGE}}
          npm run deploy ${{secrets.BLOG_REPO}}